Id feature accountform
redacademy/voicestory-winter-2020 pull request #22
Opened 2020-03-16 23:49 UTC by IED92

Created form components and Home page

2020-03-17 16:25 UTC, siddharthparmar7 requested changes
Please make changes to your code so that it doesn't throw errors. Make sure when you submit a pull request for review it is a complete feature. Thank you.

2020-03-17 16:25 UTC, siddharthparmar7 commented on client/js/components/LoginForm/LoginForm.js
> +  //   const {signIn} = React.useContext(AuthContext);
remove commented code if not needed.

2020-03-17 16:25 UTC, siddharthparmar7 commented on client/js/components/SignUpForm/SignUp.js
> +  //   const {signUp} = React.useContext(AuthContext);
same as above.

2020-03-17 16:25 UTC, siddharthparmar7 commented on client/js/components/SignUpForm/SignUp.js
> +        onPress={() => signUp({firstName, lastName, email, password})}
there is no method called signUp in your code. Please define signUp. Make sure when we merge your code it doesn't throw any errors.

2020-03-17 16:25 UTC, siddharthparmar7 commented on client/js/components/LoginForm/LoginForm.js
> +      <Button title="Login" onPress={() => signIn({email, password})} />
signIn method is missing. Please add it.

2020-03-17 23:55 UTC, KieranDevlin submitted a review, later dismissed

2020-03-18 16:32 UTC, siddharthparmar7 commented
Please resolve all the merge conflicts.

2020-03-18 16:47 UTC, KieranDevlin approved these changes
Merge conflicts corrected

2020-03-18 16:51 UTC, siddharthparmar7 approved these changes

2020-03-18 16:51 UTC, merged